FROM gradle:6.7.1-jdk8 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle installDist --no-daemon

#FROM openjdk:8-jre-slim

#EXPOSE 8080

RUN mkdir /app

#COPY --from=build /home/gradle/src/build/libs/*.jar /app/
RUN cp -r /home/gradle/src/build/install/gradle-docker-sample /app/
WORKDIR /app/gradle-docker-sample


ENTRYPOINT ["java", "-jar", "gradle-docker-sample-0.1.jar"]