FROM gradle:6.7.1-jdk8 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle installDist --no-daemon

#FROM openjdk:8-jre-slim

#EXPOSE 8080

RUN mkdir /app

#COPY --from=build /home/gradle/src/build/libs/*.jar /app/
RUN cp -r /home/gradle/src/build/install/gradle-docker-sample /app/
WORKDIR /app/gradle-docker-sample
ENV CLASSPATH ./lib/*.jar

#COPY /home/gradle/src/build/libs/*.jar /app/
#COPY ./credentials/google-drive /app/PhotoChef-1.0/bin/credentials/google-drive
#COPY ./credentials/google-photos /app/PhotoChef-1.0/bin/credentials/google-photos

#ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app/spring-boot-application.jar"]